update

diff --git a/infra-cicd/90-cdn/Jenkinsfile b/infra-cicd/90-cdn/Jenkinsfile
--- a/infra-cicd/90-cdn/Jenkinsfile
+++ b/infra-cicd/90-cdn/Jenkinsfile
@@ -57,15 +57,25 @@ pipeline {
                             'infra-cicd/20-sg',
                             'infra-cicd/10-vpc'
                         ]
-                        for (subdir in directories) {
-                            echo "Destroying resources in directory: ${subdir}"
-                            dir("${subdir}") {
-                                sh """
-                                    terraform init -reconfigure
-                                    terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
-                                """
-                            }
+                        // Reverse order to destroy dependencies safely
+                        directories.reverse().each { dir ->
+                            echo "Destroying resources in directory: ${dir}"
+                            sh """
+                                cd ${dir} || { echo "Directory ${dir} not found"; exit 1; }
+                                terraform init -reconfigure
+                                terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
+                                cd - 
+                            """
                         }
+                        // for (subdir in directories) {
+                        //     echo "Destroying resources in directory: ${subdir}"
+                        //     dir("${subdir}") {
+                        //         sh """
+                        //             terraform init -reconfigure
+                        //             terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
+                        //         """
+                        //     }
+                        // }
                     }
                 }
             }
